[package]
name = "llmaker"
version = "0.1.0"
authors = ["puripuri2100 <36466996+puripuri2100@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2"
